# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "木叶教育"
email: "ruibin_edu@foxmail.com"
description: "木叶教育"
description_en: "Love Chinese tranditional culture, Love design."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.muyeedu.com" # the base hostname & protocol for your site
twitter_username: futurefriendly
github_username:  futurefriendly

# Build settings
markdown: kramdown

sass:
    style: compressed

categories: [note, activity]